<H1>Combine datasets 1 (expts 1 and 2) and dataset 2<H1>

1. Import the needed packages.

In [1]:
import os
import fnmatch
import pandas as pd
import numpy as np
import itertools

2. Read and store the datasets as dataframes

In [2]:
dataset1_expt1 = pd.read_csv('/Users/saramosteller/Library/CloudStorage/OneDrive-Personal/Projects/Residuals/Final_Datasets/Dataset_1/Experiment_1_Datasets/Experiment_1_trial_data.csv')
dataset1_expt1.head()

,id,tired,attention,trial_num,block,trial_num_within_block,set_size,change,response,rt,...,item_location_7_x,item_location_8_x,item_location_1_y,item_location_2_y,item_location_3_y,item_location_4_y,item_location_5_y,item_location_6_y,item_location_7_y,item_location_8_y
0,100,2.0,3.0,1,1,1,6,0,1,0.976718,...,NaN,NaN,251.107023,190.331104,455.602007,576.638796,474.143813,492.170569,NaN,NaN
1,100,2.0,3.0,2,1,2,4,1,1,0.653491,...,NaN,NaN,312.397993,319.093645,530.799331,451.996656,NaN,NaN,NaN,NaN
2,100,2.0,3.0,3,1,3,4,1,1,0.567030,...,NaN,NaN,250.591973,246.986622,451.996656,489.595318,NaN,NaN,NaN,NaN
3,100,2.0,3.0,4,1,4,4,1,1,0.652047,...,NaN,NaN,179.000000,204.237458,546.765886,562.732441,NaN,NaN,NaN,NaN
4,100,2.0,3.0,5,1,5,6,0,1,0.589708,...,NaN,NaN,199.086957,210.933110,460.237458,451.996656,583.849498,544.190635,NaN,NaN

In [3]:
dataset1_expt2 = pd.read_csv('/Users/saramosteller/Library/CloudStorage/OneDrive-Personal/Projects/Residuals/Final_Datasets/Dataset_1/Experiment_2_Datasets/Experiment_2_trial_data.csv')
dataset1_expt2.head()

,id,session,place,time_of_day,tired,attention,trial_num,block,trial_num_within_block,set_size,...,item_location_7_x,item_location_8_x,item_location_1_y,item_location_2_y,item_location_3_y,item_location_4_y,item_location_5_y,item_location_6_y,item_location_7_y,item_location_8_y
0,1,60,2,1.0,5.0,5.0,1,1,1,8,...,229.000000,796.153846,241.695652,225.260870,510.478261,461.173913,325.086956,188.739130,590.217391,446.565217
1,1,60,2,1.0,5.0,5.0,2,1,2,8,...,277.521739,748.862876,257.521739,201.521739,568.304348,524.478261,323.260870,177.782609,528.739130,543.347826
2,1,60,2,1.0,5.0,5.0,3,1,3,6,...,NaN,NaN,167.434783,205.782609,601.173913,578.652174,566.478261,437.434783,NaN,NaN
3,1,60,2,1.0,5.0,5.0,4,1,4,4,...,NaN,NaN,233.782609,330.565217,550.652174,544.565217,NaN,NaN,NaN,NaN
4,1,60,2,1.0,5.0,5.0,5,1,5,8,...,369.173913,863.712375,312.913044,211.260870,579.260870,537.260870,189.347826,204.565217,460.565217,530.565217

In [4]:
dataset2 = pd.read_csv('/Users/saramosteller/Library/CloudStorage/OneDrive-Personal/Projects/Residuals/Papers/Manuscript_1_VWM/Code/Python/Python_Compilation/Trial_Data.csv')
dataset2.head()

,Unnamed: 0,id,trial_num,set_size,change,response,rt,stim_duration,test_location_x,test_location_y
0,0,1,0,4,0,1,1381,150,-300,-200
1,1,1,1,8,1,0,1034,150,300,-100
2,2,1,2,4,0,1,837,150,-100,200
3,3,1,3,8,0,1,744,150,-200,-200
4,4,1,4,8,0,1,678,150,-300,200

In [5]:
dataset1_expt1.head()

,id,tired,attention,trial_num,block,trial_num_within_block,set_size,change,response,rt,...,item_location_7_x,item_location_8_x,item_location_1_y,item_location_2_y,item_location_3_y,item_location_4_y,item_location_5_y,item_location_6_y,item_location_7_y,item_location_8_y
0,100,2.0,3.0,1,1,1,6,0,1,0.976718,...,NaN,NaN,251.107023,190.331104,455.602007,576.638796,474.143813,492.170569,NaN,NaN
1,100,2.0,3.0,2,1,2,4,1,1,0.653491,...,NaN,NaN,312.397993,319.093645,530.799331,451.996656,NaN,NaN,NaN,NaN
2,100,2.0,3.0,3,1,3,4,1,1,0.567030,...,NaN,NaN,250.591973,246.986622,451.996656,489.595318,NaN,NaN,NaN,NaN
3,100,2.0,3.0,4,1,4,4,1,1,0.652047,...,NaN,NaN,179.000000,204.237458,546.765886,562.732441,NaN,NaN,NaN,NaN
4,100,2.0,3.0,5,1,5,6,0,1,0.589708,...,NaN,NaN,199.086957,210.933110,460.237458,451.996656,583.849498,544.190635,NaN,NaN

3. Check dataset properties

Check that conditions are counterbalanced within blocks/sessions before removing trials from the dataset 1 experiments.

In [6]:
#In dataset 1, expt 1, check to see if conditions are counterbalanced within each block
dataset1_expt1.groupby(['id', 'block', 'change', 'set_size']).count() #The conditions are counterbalanced within each block

                           tired  attention  trial_num  \
id  block change set_size
1   1     0      4            10         10         10
                 6            10         10         10
                 8            10         10         10
          1      4            10         10         10
                 6            10         10         10
...                          ...        ...        ...
141 9     0      6            10         10         10
                 8            10         10         10
          1      4            10         10         10
                 6            10         10         10
                 8            10         10         10

                           trial_num_within_block  response  rt  stim_size  \
id  block change set_size
1   1     0      4                             10        10  10         10
                 6                             10        10  10         10
                 8                             10        10  10         10
          1      4                             10        10  10         10
                 6                             10        10  10         10
...                                           ...       ...  ..        ...
141 9     0      6                             10        10  10         10
                 8                             10        10  10         10
          1      4                             10        10  10         10
                 6                             10        10  10         10
                 8                             10        10  10         10

                           stim_duration  fixation_size  intertrial_interval  \
id  block change set_size
1   1     0      4                    10             10                   10
                 6                    10             10                   10
                 8                    10             10                   10
          1      4                    10             10                   10
                 6                    10             10                   10
...                                  ...            ...                  ...
141 9     0      6                    10             10                   10
                 8                    10             10                   10
          1      4                    10             10                   10
                 6                    10             10                   10
                 8                    10             10                   10

                           ...  item_location_7_x  item_location_8_x  \
id  block change set_size  ...
1   1     0      4         ...                  0                  0
                 6         ...                  0                  0
                 8         ...                 10                 10
          1      4         ...                  0                  0
                 6         ...                  0                  0
...                        ...                ...                ...
141 9     0      6         ...                  0                  0
                 8         ...                 10                 10
          1      4         ...                  0                  0
                 6         ...                  0                  0
                 8         ...                 10                 10

                           item_location_1_y  item_location_2_y  \
id  block change set_size
1   1     0      4                        10                 10
                 6                        10                 10
                 8                        10                 10
          1      4                        10                 10
                 6                        10                 10
...                                      ...                ...
141 9     0      6                        10                 10
                 8                        10                 10
          1      4                        10                 10
                 6                        10                 10
                 8                        10                 10

                           item_location_3_y  item_location_4_y  \
id  block change set_size
1   1     0      4                        10                 10
                 6                        10                 10
                 8                        10                 10
          1      4                        10                 10
                 6                        10                 10
...                                      ...                ...
141 9     0      6                        10                 10
                 8                        10                 10
          1      4                        10                 10
                 6                        10                 10
                 8                        10                 10

                           item_location_5_y  item_location_6_y  \
id  block change set_size
1   1     0      4                         0                  0
                 6                        10                 10
                 8                        10                 10
          1      4                         0                  0
                 6                        10                 10
...                                      ...                ...
141 9     0      6                        10                 10
                 8                        10                 10
          1      4                         0                  0
                 6                        10                 10
                 8                        10                 10

                           item_location_7_y  item_location_8_y
id  block change set_size
1   1     0      4                         0                  0
                 6                         0                  0
                 8                        10                 10
          1      4                         0                  0
                 6                         0                  0
...                                      ...                ...
141 9     0      6                         0                  0
                 8                        10                 10
          1      4                         0                  0
                 6                         0                  0
                 8                        10                 10

[7182 rows x 41 columns]

In [7]:
#In dataset 2, expt 2, check to see if conditions are counterbalanced within each session
dataset1_expt2.groupby(['id', 'session', 'block', 'change', 'set_size']).count() #The conditions are counterbalanced within each session

                                  place  time_of_day  tired  attention  \
id session block change set_size
1  1       1     0      4             4            4      4          4
                        6             4            4      4          4
                        8             4            4      4          4
                 1      4             4            4      4          4
                        6             4            4      4          4
...                                 ...          ...    ...        ...
99 60      5     0      6             4            4      4          4
                        8             4            4      4          4
                 1      4             4            4      4          4
                        6             4            4      4          4
                        8             4            4      4          4

                                  trial_num  trial_num_within_block  response  \
id session block change set_size
1  1       1     0      4                 4                       4         4
                        6                 4                       4         4
                        8                 4                       4         4
                 1      4                 4                       4         4
                        6                 4                       4         4
...                                     ...                     ...       ...
99 60      5     0      6                 4                       4         4
                        8                 4                       4         4
                 1      4                 4                       4         4
                        6                 4                       4         4
                        8                 4                       4         4

                                  rt  stim_size  stim_duration  ...  \
id session block change set_size                                ...
1  1       1     0      4          4          4              4  ...
                        6          4          4              4  ...
                        8          4          4              4  ...
                 1      4          4          4              4  ...
                        6          4          4              4  ...
...                               ..        ...            ...  ...
99 60      5     0      6          4          4              4  ...
                        8          4          4              4  ...
                 1      4          4          4              4  ...
                        6          4          4              4  ...
                        8          4          4              4  ...

                                  item_location_7_x  item_location_8_x  \
id session block change set_size
1  1       1     0      4                         0                  0
                        6                         0                  0
                        8                         4                  4
                 1      4                         0                  0
                        6                         0                  0
...                                             ...                ...
99 60      5     0      6                         0                  0
                        8                         4                  4
                 1      4                         0                  0
                        6                         0                  0
                        8                         4                  4

                                  item_location_1_y  item_location_2_y  \
id session block change set_size
1  1       1     0      4                         4                  4
                        6                         4                  4
                        8                         4                  4
                 1      4                         4                  4
                        6                         4                  4
...                                             ...                ...
99 60      5     0      6                         4                  4
                        8                         4                  4
                 1      4                         4                  4
                        6                         4                  4
                        8                         4                  4

                                  item_location_3_y  item_location_4_y  \
id session block change set_size
1  1       1     0      4                         4                  4
                        6                         4                  4
                        8                         4                  4
                 1      4                         4                  4
                        6                         4                  4
...                                             ...                ...
99 60      5     0      6                         4                  4
                        8                         4                  4
                 1      4                         4                  4
                        6                         4                  4
                        8                         4                  4

                                  item_location_5_y  item_location_6_y  \
id session block change set_size
1  1       1     0      4                         0                  0
                        6                         4                  4
                        8                         4                  4
                 1      4                         0                  0
                        6                         4                  4
...                                             ...                ...
99 60      5     0      6                         4                  4
                        8                         4                  4
                 1      4                         0                  0
                        6                         4                  4
                        8                         4                  4

                                  item_location_7_y  item_location_8_y
id session block change set_size
1  1       1     0      4                         0                  0
                        6                         0                  0
                        8                         4                  4
                 1      4                         0                  0
                        6                         0                  0
...                                             ...                ...
99 60      5     0      6                         0                  0
                        8                         4                  4
                 1      4                         0                  0
                        6                         0                  0
                        8                         4                  4

[73470 rows x 43 columns]

Compare the mean, midpoint and median of the x and y test locations.

In [8]:
dataset1_expt1['test_location_x'].mean()

np.float64(522.5390084002)

In [9]:
dataset1_expt1[['item_location_1_x', 'item_location_2_x', 'item_location_3_x', 'item_location_4_x', 'item_location_5_x', 'item_location_6_x', 'item_location_7_x', 'item_location_8_x']].mean(axis=0) #The overall mean is 522

item_location_1_x    347.690158
item_location_2_x    695.439720
item_location_3_x    348.051842
item_location_4_x    696.153602
item_location_5_x    348.337909
item_location_6_x    695.379563
item_location_7_x    348.013032
item_location_8_x    695.525283
dtype: float64

In [10]:
dataset1_expt1['test_location_x'].min()

np.float64(222.0)

In [11]:
dataset1_expt1['test_location_x'].max()

np.float64(1016.0)

In [12]:
dataset1_expt1['test_location_x'].median() #Mean = 522, median = 564, midpoint = 397

np.float64(564.605351170569)

In [13]:
dataset1_expt1[['item_location_1_y', 'item_location_2_y', 'item_location_3_y', 'item_location_4_y', 'item_location_5_y', 'item_location_6_y', 'item_location_7_y', 'item_location_8_y']].mean(axis=0) #The total mean is 409.5

item_location_1_y    262.212645
item_location_2_y    262.272677
item_location_3_y    524.473968
item_location_4_y    524.409820
item_location_5_y    328.417311
item_location_6_y    328.565325
item_location_7_y    524.782215
item_location_8_y    524.651781
dtype: float64

In [14]:
dataset1_expt1['test_location_y'].mean()

np.float64(394.1139714916205)

In [15]:
dataset1_expt1['test_location_y'].min()

np.float64(179.0)

In [16]:
dataset1_expt1['test_location_y'].max()

np.float64(803.0)

In [17]:
dataset1_expt1['test_location_y'].median() #Mean = 394, median = 437, midpoint = 312

np.float64(437.060200668896)

4. Format each dataset/experiment with overlapping columns

In [18]:
dataset1_expt1.shape

(72900, 45)

In [19]:
#dataset1_expt1['id'] = pd.to_numeric(dataset1_expt1['id'])
#dataset1_expt1['id'].astype('category')
len(dataset1_expt1['id'].unique()) #Two ids are being read as duplicates of another id

133

In [20]:
#Choose/format rows and columns for dataset1_expt1

#Add or standardize columns
dataset1_expt1['study'] = 1 #Xu et al., 2018
dataset1_expt1['experiment'] = 1 #Expt 1
dataset1_expt1['session'] = 1 
dataset1_expt1['distance_from_monitor'] = 60 #ms
dataset1_expt1['stim_size'] = 1.775 #average degrees of visual angle
dataset1_expt1['fixation_size'] = 0.415 #average degrees of visual angle
dataset1_expt1['stim_duration'] = 150 #ms
dataset1_expt1['intertrial_interval'] = 1000 #ms
dataset1_expt1['retention_interval'] = 1000 #ms
dataset1_expt1['break_duration'] = 60000 #ms

#create the final location variables
dataset1_expt1['test_location_x_from_center'] = dataset1_expt1['test_location_x'] - 522 #pixels from the mean
dataset1_expt1['test_location_y_from_center'] = dataset1_expt1['test_location_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_1_x_from_center'] = dataset1_expt1['item_location_1_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_1_y_from_center'] = dataset1_expt1['item_location_1_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_2_x_from_center'] = dataset1_expt1['item_location_2_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_2_y_from_center'] = dataset1_expt1['item_location_2_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_3_x_from_center'] = dataset1_expt1['item_location_3_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_3_y_from_center'] = dataset1_expt1['item_location_3_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_4_x_from_center'] = dataset1_expt1['item_location_4_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_4_y_from_center'] = dataset1_expt1['item_location_4_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_5_x_from_center'] = dataset1_expt1['item_location_5_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_5_y_from_center'] = dataset1_expt1['item_location_5_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_6_x_from_center'] = dataset1_expt1['item_location_6_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_6_y_from_center'] = dataset1_expt1['item_location_6_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_7_x_from_center'] = dataset1_expt1['item_location_7_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_7_y_from_center'] = dataset1_expt1['item_location_7_y'] - 409 #pixels from the mean
dataset1_expt1['item_location_8_x_from_center'] = dataset1_expt1['item_location_8_x'] - 522 #pixels from the mean
dataset1_expt1['item_location_8_y_from_center'] = dataset1_expt1['item_location_8_y'] - 409 #pixels from the mean

#Color values are as follows:
#Red (1): 255 0 0 , 
#Green (2): 0 255 0
#Blue (3): 0 0 255
#Magenta (5): 255 0 255
#Yellow (4): 255 255 0
#Cyan (6): 0 255 255 
#Orange (9): 255, 128, 0
#White (7): 255, 255, 255
#Black (8): 1, 1, 1

#Arrange the dataframe by id and then block
dataset1_expt1 = dataset1_expt1.sort_values(by=['id', 'block'])

#Renumber the IDs from 1:135 with itertools
n = 540
# repeat(i, n) creates an iterator that yields i, n times
# chain.from_iterable flattens these iterators into a single list
dataset1_expt1['id_renumbered'] = list(itertools.chain.from_iterable(itertools.repeat(i, n) for i in range(1, 136))) #because there are 135 participants

#Delete the original id column
dataset1_expt1 = dataset1_expt1.drop('id', axis=1)
dataset1_expt1['id'] = dataset1_expt1['id_renumbered']
dataset1_expt1 = dataset1_expt1.drop('id_renumbered', axis=1)

#Eliminate all but the first 160 trials, so that there are 120 trials of set size 4 and 8
dataset1_expt1_trimmed = dataset1_expt1.groupby('id').head(160).reset_index(drop=True)

#Select the overlapping columns
dataset1_expt1_trimmed = dataset1_expt1_trimmed[['study', 'experiment', 'id', 'trial_num', 'block', 'trial_num_within_block', 'set_size', 'change', 'response', 'rt', 'fixation_size', 'stim_size', 'stim_duration', 'retention_interval', 'distance_from_monitor', 'test_location_x_from_center', 'test_location_y_from_center']]

In [21]:
len(dataset1_expt1['id'].unique())

135

In [22]:
dataset1_expt1.shape

(72900, 67)

In [23]:
#Option to write the dataset1_expt1 with the full set of variable and renumbered IDs
dataset1_expt1_final = dataset1_expt1[['study', 'experiment', 'id', 'tired', 'attention', 'trial_num', 'block', 'trial_num_within_block',
     'set_size', 'change', 'response', 'rt', 'fixation_size', 'stim_size', 'stim_duration',
     'retention_interval', 'intertrial_interval', 'break_duration', 'min_distance', 'distance_from_monitor', 'first_test_color',
     'second_test_color', 'test_location_x_from_center', 'test_location_y_from_center', 'item_color_1', 'item_color_2', 'item_color_3', 'item_color_4',
     'item_color_5', 'item_color_6', 'item_color_7', 'item_color_8', 'item_location_1_x_from_center',
     'item_location_2_x_from_center', 'item_location_3_x_from_center', 'item_location_4_x_from_center', 'item_location_5_x_from_center',
     'item_location_6_x_from_center', 'item_location_7_x_from_center', 'item_location_8_x_from_center', 'item_location_1_y_from_center',
     'item_location_2_y_from_center', 'item_location_3_y_from_center', 'item_location_4_y_from_center', 'item_location_5_y_from_center',
     'item_location_6_y_from_center', 'item_location_7_y_from_center', 'item_location_8_y_from_center']]
dataset1_expt1_final.to_csv('Dataset1_expt1_formatted_data.csv')

In [24]:
dataset1_expt1_trimmed.shape #Make sure there are 16200 out of the original 72900 rows left

(21600, 17)

In [25]:
len(dataset1_expt2['id'].unique()) #This one is already ok with 79 unique IDs

79

In [26]:
dataset1_expt2.shape

(293880, 48)

In [27]:
dataset1_expt2[['item_location_1_x', 'item_location_2_x', 'item_location_3_x', 'item_location_4_x', 'item_location_5_x', 'item_location_6_x', 'item_location_7_x', 'item_location_8_x']].mean(axis=0) #The overall mean is 681

item_location_1_x    428.820345
item_location_2_x    932.159622
item_location_3_x    428.681978
item_location_4_x    932.514537
item_location_5_x    428.735759
item_location_6_x    932.580649
item_location_7_x    428.667183
item_location_8_x    931.784715
dtype: float64

In [28]:
dataset1_expt2[['test_location_x']].mean() #mean is 681

test_location_x    681.073941
dtype: float64

In [29]:
dataset1_expt2[['item_location_1_y', 'item_location_2_y', 'item_location_3_y', 'item_location_4_y', 'item_location_5_y', 'item_location_6_y', 'item_location_7_y', 'item_location_8_y']].mean(axis=0) #The overall mean is 425

item_location_1_y    255.847199
item_location_2_y    256.096513
item_location_3_y    556.295690
item_location_4_y    556.375813
item_location_5_y    331.209576
item_location_6_y    331.291107
item_location_7_y    556.616486
item_location_8_y    556.112056
dtype: float64

In [30]:
dataset1_expt2[['test_location_y']].mean() #mean is 406

test_location_y    406.154728
dtype: float64

In [31]:
#Choose/format rows and columns for dataset1_expt2

#Add or standardize columns
dataset1_expt2['stim_size'] = 1.37 #average degrees of visual angle
dataset1_expt2['fixation_size'] = 0.3 #degrees of visual angle
dataset1_expt2['stim_duration'] = 150 #ms
dataset1_expt2['retention_interval'] = 1000 #ms
dataset1_expt2['distance_from_monitor'] = 60 #ms
dataset1_expt2['study'] = 1 #Xu et al., 2018
dataset1_expt2['experiment'] = 2 #Expt 2

#create the final location variables
dataset1_expt2['test_location_x_from_center'] = dataset1_expt2['test_location_x'] - 681 #pixels from the mean
dataset1_expt2['test_location_y_from_center'] = dataset1_expt2['test_location_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_1_x_from_center'] = dataset1_expt2['item_location_1_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_1_y_from_center'] = dataset1_expt2['item_location_1_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_2_x_from_center'] = dataset1_expt2['item_location_2_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_2_y_from_center'] = dataset1_expt2['item_location_2_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_3_x_from_center'] = dataset1_expt2['item_location_3_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_3_y_from_center'] = dataset1_expt2['item_location_3_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_4_x_from_center'] = dataset1_expt2['item_location_4_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_4_y_from_center'] = dataset1_expt2['item_location_4_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_5_x_from_center'] = dataset1_expt2['item_location_5_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_5_y_from_center'] = dataset1_expt2['item_location_5_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_6_x_from_center'] = dataset1_expt2['item_location_6_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_6_y_from_center'] = dataset1_expt2['item_location_6_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_7_x_from_center'] = dataset1_expt2['item_location_7_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_7_y_from_center'] = dataset1_expt2['item_location_7_y'] - 425 #pixels from the mean
dataset1_expt2['item_location_8_x_from_center'] = dataset1_expt2['item_location_8_x'] - 681 #pixels from the mean
dataset1_expt2['item_location_8_y_from_center'] = dataset1_expt1['item_location_8_y'] - 425 #pixels from the mean

#Color values are as follows:
#Red (1): 255 0 0 , 
#Green (2): 0 255 0
#Blue (3): 0 0 255
#Magenta (5): 255 0 255
#Yellow (4): 255 255 0
#Cyan (6): 0 255 255 
#Orange (9): 255, 128, 0
#White (7): 255, 255, 255
#Black (8): 1, 1, 1

#Reorder and standardize the session names and change the 'session' variable to 'day'
dataset1_expt2['day'] = dataset1_expt2['session']
dataset1_expt2 = dataset1_expt2.drop('session', axis=1)
dataset1_expt2 = dataset1_expt2.sort_values(by=['id', 'day'])


#Renumber the sessions from 1:31 with itertools
n = 120
# repeat(i, n) creates an iterator that yields i, n times
# chain.from_iterable flattens these iterators into a single list 
session = list(itertools.chain.from_iterable(itertools.repeat(i, n) for i in range(1, 32))) #because there are 31 sessions per participant
session_col = session * 79
dataset1_expt2['session'] = session_col


#Eliminate all but the first session (120 trials on the first day)
dataset1_expt2_trimmed = dataset1_expt2.loc[dataset1_expt2['session'] == 1]

#Select the overlapping columns
dataset1_expt2_trimmed = dataset1_expt2_trimmed[['study', 'experiment', 'id', 'trial_num', 'block', 'trial_num_within_block', 'set_size', 'change', 'response', 'rt', 'fixation_size', 'stim_size', 'stim_duration', 'retention_interval', 'distance_from_monitor', 'test_location_x_from_center', 'test_location_y_from_center']]

In [32]:
#Make sure there are only rows
dataset1_expt2_trimmed.shape #Make sure there are 9480 out of the original 293880

(9480, 17)

In [33]:
#Option to write the dataset1_expt2 with the full set of variable
dataset1_expt2_final = dataset1_expt2[['study', 'experiment', 'id', 'day', 'session', 'tired', 'attention', 'trial_num', 'block', 'trial_num_within_block',
     'set_size', 'change', 'response', 'rt', 'fixation_size', 'stim_size', 'stim_duration',
     'retention_interval', 'intertrial_interval', 'break_duration', 'min_distance', 'distance_from_monitor', 'first_test_color',
     'second_test_color', 'test_location_x_from_center', 'test_location_y_from_center', 'item_color_1', 'item_color_2', 'item_color_3', 'item_color_4',
     'item_color_5', 'item_color_6', 'item_color_7', 'item_color_8', 'item_location_1_x_from_center',
     'item_location_2_x_from_center', 'item_location_3_x_from_center', 'item_location_4_x_from_center', 'item_location_5_x_from_center',
     'item_location_6_x_from_center', 'item_location_7_x_from_center', 'item_location_8_x_from_center', 'item_location_1_y_from_center',
     'item_location_2_y_from_center', 'item_location_3_y_from_center', 'item_location_4_y_from_center', 'item_location_5_y_from_center',
     'item_location_6_y_from_center', 'item_location_7_y_from_center', 'item_location_8_y_from_center']]
dataset1_expt2_final.to_csv('Dataset1_expt2_formatted_data.csv')

In [34]:
#Choose/format rows and columns for dataset2

#Add additional variables
dataset2['stim_size'] = 0.4 #degrees of visual angle
dataset2['fixation_size'] = 1.3 #degrees of visual angle
dataset2['retention_interval'] = 900 #ms
dataset2['distance_from_monitor'] = 60 #cm
dataset2['study'] = 2 #Balaban et al., 2019
dataset2['experiment'] = 1 
dataset2['session'] = 1 #Although we don't know whether they were a repeat participant or not
dataset2['block'] = 1 
dataset2['trial_num_within_block'] =  dataset2['trial_num']
dataset2['test_location_x_from_center'] =  dataset2['test_location_x']
dataset2['test_location_y_from_center'] =  dataset2['test_location_y']



dataset2 = dataset2[['study', 'experiment', 'id', 'trial_num', 'block', 'trial_num_within_block', 'set_size', 'change', 'response', 'rt', 'fixation_size', 'stim_size', 'stim_duration', 'retention_interval', 'distance_from_monitor', 'test_location_x_from_center', 'test_location_y_from_center']]

In [35]:
len(dataset2['id'].unique()) #3838 IDs

3838

In [36]:
dataset2.shape

(460866, 17)

5. Create and write the combined datasets

In [37]:
#Create a version with the trimmed datasets
data = pd.concat([dataset1_expt1_trimmed, dataset1_expt2_trimmed, dataset2])
#Create the unique id for each dataset in the combined file
data['id_combined'] = (data['id'] != data['id'].shift()).cumsum()
#Delete the original id column
data = data.drop('id', axis=1)
data['id'] = data['id_combined']
data = data.drop('id_combined', axis=1)
data.head()

,study,experiment,trial_num,block,trial_num_within_block,set_size,change,response,rt,fixation_size,stim_size,stim_duration,retention_interval,distance_from_monitor,test_location_x_from_center,test_location_y_from_center,id
0,1,1,1,1,1,6,1,0,4.344281,0.415,1.775,150,1000,60,-156.919732,96.561873,1
1,1,1,2,1,2,6,0,1,5.743140,0.415,1.775,150,1000,60,259.327759,-114.628763,1
2,1,1,3,1,3,6,0,0,1.431351,0.415,1.775,150,1000,60,-157.719064,179.484950,1
3,1,1,4,1,4,8,1,1,2.025998,0.415,1.775,150,1000,60,91.568562,-97.117057,1
4,1,1,5,1,5,4,0,0,0.957353,0.415,1.775,150,1000,60,-196.886288,177.424749,1

In [38]:
#Select and order the columns to keep
data_final = data[['study', 'experiment', 'id', 'trial_num','set_size', 'change', 'response', 'rt', 'stim_size', 'fixation_size', 'stim_duration', 'retention_interval', 'distance_from_monitor', 'test_location_x_from_center', 'test_location_y_from_center']]
data_final.head()

,study,experiment,id,trial_num,set_size,change,response,rt,stim_size,fixation_size,stim_duration,retention_interval,distance_from_monitor,test_location_x_from_center,test_location_y_from_center
0,1,1,1,1,6,1,0,4.344281,1.775,0.415,150,1000,60,-156.919732,96.561873
1,1,1,1,2,6,0,1,5.743140,1.775,0.415,150,1000,60,259.327759,-114.628763
2,1,1,1,3,6,0,0,1.431351,1.775,0.415,150,1000,60,-157.719064,179.484950
3,1,1,1,4,8,1,1,2.025998,1.775,0.415,150,1000,60,91.568562,-97.117057
4,1,1,1,5,4,0,0,0.957353,1.775,0.415,150,1000,60,-196.886288,177.424749

In [39]:
len(data_final['id'].unique()) #There should be 4052 unique IDs

4052

In [40]:
data_final.shape #Should have 486546 rows

(491946, 15)

In [41]:
#Write the processed trial-level dataset to a new csv file
data_final.to_csv('Combined_trial_data_with_120_4or8_trials_per_individual_dataset.csv')

In [42]:
#Create a version with the full datasets
data_full = pd.concat([dataset1_expt1, dataset1_expt2, dataset2])
#Create the unique id for each dataset in the combined file
data_full['id_combined'] = (data_full['id'] != data_full['id'].shift()).cumsum()
#Delete the original id column
data_full = data_full.drop('id', axis=1)
data_full['id'] = data_full['id_combined']
data_full = data_full.drop('id_combined', axis=1)
data_full.head()

,tired,attention,trial_num,block,trial_num_within_block,set_size,change,response,rt,stim_size,...,item_location_6_x_from_center,item_location_6_y_from_center,item_location_7_x_from_center,item_location_7_y_from_center,item_location_8_x_from_center,item_location_8_y_from_center,place,time_of_day,day,id
25380,3.0,4.0,1,1,1,6,1,0,4.344281,1.775,...,188.692308,-188.280936,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
25381,3.0,4.0,2,1,2,6,0,1,5.743140,1.775,...,259.327759,-114.628763,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
25382,3.0,4.0,3,1,3,6,0,0,1.431351,1.775,...,202.337793,90.381271,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
25383,3.0,4.0,4,1,4,8,1,1,2.025998,1.775,...,183.073579,-155.317726,-297.602007,69.264214,245.682274,66.688963,NaN,NaN,NaN,1
25384,3.0,4.0,5,1,5,4,0,0,0.957353,1.775,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [43]:
#Select and order the columns to keep
data_full['block'] = data_full['block'].fillna(1)
data_final_full = data_full[['study', 'experiment', 'id', 'session', 'trial_num', 'block', 'trial_num_within_block','set_size', 'change', 'response', 'rt', 'fixation_size', 'stim_size', 'stim_duration','retention_interval', 'distance_from_monitor', 'test_location_x_from_center', 'test_location_y_from_center']]
data_final_full.head()

,study,experiment,id,session,trial_num,block,trial_num_within_block,set_size,change,response,rt,fixation_size,stim_size,stim_duration,retention_interval,distance_from_monitor,test_location_x_from_center,test_location_y_from_center
25380,1,1,1,1.0,1,1,1,6,1,0,4.344281,0.415,1.775,150,1000,60,-156.919732,96.561873
25381,1,1,1,1.0,2,1,2,6,0,1,5.743140,0.415,1.775,150,1000,60,259.327759,-114.628763
25382,1,1,1,1.0,3,1,3,6,0,0,1.431351,0.415,1.775,150,1000,60,-157.719064,179.484950
25383,1,1,1,1.0,4,1,4,8,1,1,2.025998,0.415,1.775,150,1000,60,91.568562,-97.117057
25384,1,1,1,1.0,5,1,5,4,0,0,0.957353,0.415,1.775,150,1000,60,-196.886288,177.424749

In [44]:
len(data_final_full['id'].unique()) #There should be 4052 unique IDs

4052

In [45]:
data_final_full.shape #Should have 827646 rows

(827646, 18)

In [46]:
data_final_full.to_csv('Combined_trial_data_with_all_trials_in_all_datasets.csv')